name: udhar_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^5.0.1
  logger: ^1.1.0
  provider: ^6.0.3
  injectable: ^2.1.0
  get_it: ^7.2.0
  dio: ^4.0.6
  pin_code_fields: ^7.4.0
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  firebase_storage: ^11.0.14
  streaming_shared_preferences: ^2.0.0
  cloud_firestore: ^4.4.3
  email_validator: ^2.1.17
  razorpay_flutter: ^1.3.4
  otpless_flutter: ^1.0.8
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0

  auto_route_generator: ^5.0.2
  injectable_generator: ^2.1.3
  flutter_launcher_icons: ^0.11.0
  flutter_gen_runner: ^5.3.2
  build_runner: ^2.4.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:
  assets:
    - assets/images/
    - assets/lotties/

  uses-material-design: true
