// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyhAzj3t3ef-_5eaUCrQ_KSIXKZS1P6nk',
    appId: '1:67534852727:web:d467574f9276e2b900ec72',
    messagingSenderId: '67534852727',
    projectId: 'udhar-app-54d07',
    authDomain: 'udhar-app-54d07.firebaseapp.com',
    storageBucket: 'udhar-app-54d07.appspot.com',
    measurementId: 'G-WKBKD2FC1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVdQgl3zu6Cms2yDyMOGwuZSgpWCdXz4s',
    appId: '1:67534852727:android:42ce15ce325285db00ec72',
    messagingSenderId: '67534852727',
    projectId: 'udhar-app-54d07',
    storageBucket: 'udhar-app-54d07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqjC6LnKbzKGWSTIbH2o4swlNRWRIUuuw',
    appId: '1:67534852727:ios:4cac153f3108fda000ec72',
    messagingSenderId: '67534852727',
    projectId: 'udhar-app-54d07',
    storageBucket: 'udhar-app-54d07.appspot.com',
    iosClientId: '67534852727-rie3o9a8jd48m5hipi56podk1ejh92ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.udharApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqjC6LnKbzKGWSTIbH2o4swlNRWRIUuuw',
    appId: '1:67534852727:ios:4cac153f3108fda000ec72',
    messagingSenderId: '67534852727',
    projectId: 'udhar-app-54d07',
    storageBucket: 'udhar-app-54d07.appspot.com',
    iosClientId: '67534852727-rie3o9a8jd48m5hipi56podk1ejh92ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.udharApp',
  );
}
