name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  
  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2.6.1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ipa
      - uses: actions/upload-artifact@v1
        with:
           name: release-api
           path: build/app/outputs/flutter-apk/release/app-release.api 

  flutter_build:
   name: Build Flutter (Android)
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with:
        java-version: "12.x"
     - uses: subosito/flutter-action@v2.6.1

     - run: flutter pub get

     - run: flutter clean

     - run: flutter build apk --release
   
     - uses: actions/upload-artifact@v1
       with:
          name: release-apk
          path: build/app/outputs/flutter-apk/release/app-release.apk    

     - run: flutter build appbundle     
     - uses: actions/upload-artifact@v1
       with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab    

